openapi: 3.0.1
info:
  title: api
  version: 0.0.1
paths:
  /v1/syncs:
    post:
      operationId: SyncService.add
      tags:
        - SyncService
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SyncNangoSyncConfig'
components:
  schemas:
    SyncNangoSyncConfig:
      type: object
      properties:
        base_url:
          type: string
        method:
          $ref: '#/components/schemas/SyncNangoHttpMethod'
        headers:
          type: object
          additionalProperties: {}
        body: {}
        query_params:
          type: object
          additionalProperties: {}
        unique_key:
          type: string
        response_path:
          type: string
        paging_cursor_request_path:
          type: string
        paging_cursor_metadata_response_path:
          type: string
        paging_cursor_object_response_path:
          type: string
        paging_url_path:
          type: string
        paging_header_link_rel:
          type: string
        auto_mapping:
          type: boolean
        mapped_table:
          type: string
        frequency:
          type: integer
        pizzly_connection_id:
          type: string
        pizzly_provider_config_key:
          type: string
        max_total:
          type: integer
        friendly_name:
          type: string
        metadata:
          type: object
          additionalProperties: {}
      required:
        - method
        - headers
        - body
        - query_params
        - metadata
    SyncNangoHttpMethod:
      type: string
      enum:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
  securitySchemes: {}
servers: []
